apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  # type: NodePort
  selector:
    app.kubernetes.io/name: python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30001
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: python-service2
# spec:
#   # type: clusterIp
#   selector:
#     app.kubernetes.io/name: python
#   ports:
#     - protocol: TCP
#       port: 8001
#       targetPort: 8000