name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          # registry: ghcr.io
          # username: "${{ secrets.DOCKERHUB_USERNAME }}"
          # password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: app/
          file: app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/homework:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/homework:latest

      - name: Create K8S Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Deploy with Helm
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            helm dependency build ./chart
            helm upgrade --install homework ./chart \
            --namespace homework \
            --create-namespace \
            --set mysql.auth.rootPassword=${{ secrets.MYSQL_PASSWORD }} \
            --set tag=${{ github.run_id }} \
            --set image=${{ secrets.DOCKERHUB_USERNAME }}/homework \
            --wait
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Output image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
